import type { Task, TaskCategory } from './taskEngine';

type MicroInput = {
  id: string;
  roomId: string;
  title: string;
  category?: TaskCategory;
  minutes: number;
  everyDays: number;
  priority: number;
  bundleKey: string;
  bundleLabel: string;
  steps: string[];
  done: string;
  tools?: string[];
  products?: string[];
  warnings?: string[];
  childFriendly?: boolean;
  guests?: boolean;
  kickstart?: boolean;
};

function micro(input: MicroInput): Task {
  return {
    id: input.id,
    roomId: input.roomId,
    title: input.title,
    category: input.category ?? 'visible',
    durationMinutes: input.minutes,
    effort: 1,
    tools: input.tools ?? ['Mikrofiberduk'],
    products: input.products,
    steps: input.steps,
    doneDefinition: [input.done],
    modes: input.guests ? ['daily', 'weekend', 'guests'] : ['daily', 'weekend'],
    childFriendly: input.childFriendly ?? true,
    safetyWarnings: input.warnings,
    depth: 'quick',
    recurrenceDays: input.everyDays,
    recommendationPriority: input.priority,
    recommendationReason: 'En liten detalj som proffs tar systematiskt och som är lätt att missa i ett vanligt pass.',
    priorityBoost: 0.25,
    bundleKey: input.bundleKey,
    bundleLabel: input.bundleLabel,
    firstUseDueImmediately: input.kickstart,
  };
}

export const microTasks: Task[] = [
  micro({ id: 'micro-kitchen-towels', roomId: 'kitchen', title: 'Byt kökshanddukar', category: 'laundry', minutes: 3, everyDays: 1, priority: 76, bundleKey: 'kitchen-textiles', bundleLabel: 'Fräscha upp kökstextilierna', tools: ['Rena kökshanddukar'], steps: ['Lägg använda kökshanddukar i tvätten.', 'Häng upp torra, rena handdukar så de kan luftas.'], done: 'Alla kökshanddukar i bruk är rena och hänger luftigt.', guests: true, kickstart: true }),
  micro({ id: 'micro-dishcloth', roomId: 'kitchen', title: 'Byt disktrasa', category: 'laundry', minutes: 2, everyDays: 1, priority: 80, bundleKey: 'kitchen-textiles', bundleLabel: 'Fräscha upp kökstextilierna', tools: ['Ren disktrasa'], steps: ['Lägg den använda trasan i tvätten.', 'Skölj eller fukta den rena trasan och häng den luftigt mellan användningarna.'], done: 'En ren disktrasa finns framme och kan torka mellan användningarna.', guests: true, kickstart: true }),
  micro({ id: 'micro-upstairs-hand-towel', roomId: 'upstairs-bathroom', title: 'Byt handhandduk i badrummet uppe', category: 'laundry', minutes: 3, everyDays: 3, priority: 74, bundleKey: 'bathroom-textiles', bundleLabel: 'Byt badrummens textilier', tools: ['Ren handhandduk'], steps: ['Lägg den använda handduken i tvätten.', 'Häng upp en ren handduk med plats att torka.'], done: 'Badrummet uppe har en ren, torr handhandduk.', guests: true, kickstart: true }),
  micro({ id: 'micro-downstairs-hand-towel', roomId: 'downstairs-bathroom', title: 'Byt handhandduk i badrummet nere', category: 'laundry', minutes: 3, everyDays: 7, priority: 66, bundleKey: 'bathroom-textiles', bundleLabel: 'Byt badrummens textilier', tools: ['Ren handhandduk'], steps: ['Byt handduken, tidigare om den är fuktig eller flitigt använd.', 'Häng den rena handduken luftigt.'], done: 'Badrummet nere har en ren, torr handhandduk.', guests: true, kickstart: true }),
  micro({ id: 'micro-shower-towels', roomId: 'upstairs-bathroom', title: 'Byt duschhanddukar', category: 'laundry', minutes: 5, everyDays: 3, priority: 72, bundleKey: 'bathroom-textiles', bundleLabel: 'Byt badrummens textilier', tools: ['Rena duschhanddukar'], steps: ['Byt handdukar efter ungefär två till tre användningar, tidigare om de inte torkar helt.', 'Häng de rena handdukarna med luft mellan.'], done: 'Aktiva duschhanddukar är rena och kan torka ordentligt.', kickstart: true }),
  micro({ id: 'micro-bath-mats', roomId: 'upstairs-bathroom', title: 'Byt badrumsmattor', category: 'laundry', minutes: 5, everyDays: 7, priority: 62, bundleKey: 'bathroom-textiles', bundleLabel: 'Byt badrummens textilier', tools: ['Rena badrumsmattor'], steps: ['Lägg fuktiga eller smutsiga mattor i tvätten.', 'Kontrollera tvättrådet och lägg fram en ren, torr matta.'], done: 'Badrumsgolvens textilmattor är rena och torra.', kickstart: true }),
  micro({ id: 'micro-bed-linen', roomId: 'bedroom-1', title: 'Byt sängkläder i en säng', category: 'laundry', minutes: 10, everyDays: 14, priority: 68, bundleKey: 'bed-textiles', bundleLabel: 'Fräscha upp en säng', tools: ['Rent underlakan', 'Rent påslakan', 'Rena örngott'], steps: ['Välj den säng som väntat längst.', 'Ta av använda textilier och vädra sängen kort.', 'Bädda med rena textilier.'], done: 'En säng är komplett renbäddad.' }),
  micro({ id: 'micro-pillowcases', roomId: 'bedroom-1', title: 'Byt örngott', category: 'laundry', minutes: 5, everyDays: 7, priority: 64, bundleKey: 'bed-textiles', bundleLabel: 'Fräscha upp en säng', tools: ['Rena örngott'], steps: ['Byt örngott i den säng som väntat längst.', 'Lägg använda örngott direkt i tvätten.'], done: 'Valda kuddar har rena örngott.' }),
  micro({ id: 'micro-sofa-throws', roomId: 'living-room', title: 'Tvätta eller vädra soffiltar', category: 'laundry', minutes: 8, everyDays: 30, priority: 48, bundleKey: 'living-textiles', bundleLabel: 'Fräscha upp vardagsrummets textilier', tools: ['Tvättkorg'], steps: ['Kontrollera tvättråden.', 'Tvätta filtar som används mycket; vädra övriga.', 'Vik tillbaka bara rena och torra filtar.'], done: 'Soffiltarna är rena eller ordentligt vädrade.' }),
  micro({ id: 'micro-cushion-covers', roomId: 'living-room', title: 'Tvätta avtagbara kuddfodral', category: 'laundry', minutes: 10, everyDays: 90, priority: 38, bundleKey: 'living-textiles', bundleLabel: 'Fräscha upp vardagsrummets textilier', tools: ['Tvättkorg'], steps: ['Välj avtagbara fodral och kontrollera tvättrådet.', 'Tvätta och låt torka enligt etiketten.', 'Sätt tillbaka helt torra fodral.'], done: 'Valda kuddfodral är rena och sitter tillbaka.' }),

  micro({ id: 'micro-microwave', roomId: 'kitchen', title: 'Torka ur mikron', category: 'hygiene', minutes: 7, everyDays: 7, priority: 70, bundleKey: 'kitchen-appliances', bundleLabel: 'Ta kökets små vitvaror', products: ['Milt diskmedel'], steps: ['Ta ut och diska den lösa tallriken.', 'Torka tak, väggar, botten och luckans insida.', 'Torka handtag och utsida.'], done: 'Mikron är fri från matstänk och produktrester.', guests: true }),
  micro({ id: 'micro-toaster-crumbs', roomId: 'kitchen', title: 'Töm brödrostens smulbricka', category: 'hygiene', minutes: 5, everyDays: 14, priority: 60, bundleKey: 'kitchen-appliances', bundleLabel: 'Ta kökets små vitvaror', tools: ['Torr borste'], steps: ['Dra ur kontakten och låt brödrosten svalna.', 'Töm smulbrickan enligt manualen.', 'Borsta bort lösa smulor och torka utsidan torrt.'], done: 'Smulbrickan är tom och korrekt monterad.', warnings: ['Sänk aldrig ner brödrosten i vatten.'] }),
  micro({ id: 'micro-coffee-station', roomId: 'kitchen', title: 'Återställ kaffestationen', category: 'hygiene', minutes: 8, everyDays: 7, priority: 62, bundleKey: 'kitchen-appliances', bundleLabel: 'Ta kökets små vitvaror', products: ['Milt diskmedel'], steps: ['Töm sump och droppbricka enligt maskinens manual.', 'Diska lösa användardelar.', 'Torka maskinens utsida och ytan under.'], done: 'Kaffestationen är ren, torr och redo att användas.' }),
  micro({ id: 'micro-kettle', roomId: 'kitchen', title: 'Torka vattenkokare och sladdzon', category: 'visible', minutes: 5, everyDays: 14, priority: 46, bundleKey: 'kitchen-appliances', bundleLabel: 'Ta kökets små vitvaror', tools: ['Mikrofiberduk'], steps: ['Dra ur kontakten och låt kannan svalna.', 'Torka utsida, handtag och bas utan att blöta eldelar.', 'Torka ytan under och ordna sladden.'], done: 'Vattenkokare, bas och ytan under är rena och torra.', warnings: ['Sänk aldrig ner bas eller kanna med eldelar i vatten.'] }),
  micro({ id: 'micro-cabinet-fronts', roomId: 'kitchen', title: 'Torka en sektion köksluckor', category: 'visible', minutes: 10, everyDays: 14, priority: 58, bundleKey: 'kitchen-surfaces', bundleLabel: 'Ta kökets vertikala ytor', products: ['Materialanpassat milt rengöringsmedel'], steps: ['Välj en sammanhängande sektion.', 'Torka uppifrån och ner.', 'Punktbehandla fettmärken och torka torrt.'], done: 'Den valda sektionens fronter är fria från synliga märken.', guests: true }),
  micro({ id: 'micro-cabinet-handles', roomId: 'kitchen', title: 'Torka kökets handtag', category: 'hygiene', minutes: 5, everyDays: 7, priority: 68, bundleKey: 'kitchen-surfaces', bundleLabel: 'Ta kökets vertikala ytor', products: ['Milt rengöringsmedel'], steps: ['Torka handtag och ytan precis runt dem.', 'Torka bort produktrester och fukt.'], done: 'Kökets mest använda handtag känns rena.', guests: true }),
  micro({ id: 'micro-backsplash', roomId: 'kitchen', title: 'Torka stänkskyddet', category: 'hygiene', minutes: 7, everyDays: 7, priority: 66, bundleKey: 'kitchen-surfaces', bundleLabel: 'Ta kökets vertikala ytor', products: ['Materialanpassat rengöringsmedel'], steps: ['Torka bort färska stänk runt häll och diskho.', 'Bearbeta fogar varsamt.', 'Eftertorka utan produktrester.'], done: 'Stänkskyddet är fritt från synligt fett och matstänk.' }),
  micro({ id: 'micro-hood-exterior', roomId: 'kitchen', title: 'Torka köksfläktens utsida', category: 'hygiene', minutes: 7, everyDays: 7, priority: 64, bundleKey: 'kitchen-surfaces', bundleLabel: 'Ta kökets vertikala ytor', products: ['Materialanpassad avfettning'], steps: ['Stäng av fläkten.', 'Torka reglage, undersida och front.', 'Eftertorka enligt ytans skötselråd.'], done: 'Fläktens utsida och reglage är fria från kladd.' }),
  micro({ id: 'micro-fridge-handles', roomId: 'kitchen', title: 'Torka kylens och frysens handtag', category: 'hygiene', minutes: 4, everyDays: 7, priority: 65, bundleKey: 'kitchen-surfaces', bundleLabel: 'Ta kökets vertikala ytor', products: ['Milt rengöringsmedel'], steps: ['Torka handtag och greppzoner.', 'Torka torrt för att undvika ränder.'], done: 'Vitvarornas greppytor känns rena.', guests: true }),
  micro({ id: 'micro-bin-lid', roomId: 'kitchen', title: 'Torka sopkärlets lock och kant', category: 'odor', minutes: 5, everyDays: 7, priority: 72, bundleKey: 'kitchen-waste', bundleLabel: 'Återställ avfallszonen', products: ['Milt rengöringsmedel'], steps: ['Ta ut påsen om det behövs.', 'Torka lock, pedal, kant och greppytor.', 'Torka torrt och sätt i rätt påse.'], done: 'Kärlets kontaktpunkter är rena och torra.', guests: true }),
  micro({ id: 'micro-wash-bin', roomId: 'kitchen', title: 'Tvätta ur ett sopkärl', category: 'odor', minutes: 12, everyDays: 30, priority: 70, bundleKey: 'kitchen-waste', bundleLabel: 'Återställ avfallszonen', tools: ['Skyddshandskar', 'Borste'], products: ['Diskmedel'], steps: ['Töm kärlet helt.', 'Tvätta insida, utsida och lock.', 'Skölj sparsamt och låt torka helt innan ny påse.'], done: 'Ett sopkärl är rent, torrt och luktfritt.' }),
  micro({ id: 'micro-recycling-station', roomId: 'kitchen', title: 'Torka återvinningsstationen', category: 'odor', minutes: 8, everyDays: 7, priority: 60, bundleKey: 'kitchen-waste', bundleLabel: 'Återställ avfallszonen', tools: ['Mikrofiberduk'], products: ['Milt rengöringsmedel'], steps: ['Ta bort fulla fraktioner.', 'Torka spill och kladd från behållare och hylla.', 'Sätt tillbaka tomma kärl sorterat.'], done: 'Återvinningszonen är ren och har plats.' }),
  micro({ id: 'micro-dishwasher-seal', roomId: 'kitchen', title: 'Torka diskmaskinens tätning', category: 'hygiene', minutes: 6, everyDays: 30, priority: 57, bundleKey: 'kitchen-appliances', bundleLabel: 'Ta kökets små vitvaror', products: ['Milt diskmedel'], steps: ['Öppna avstängd maskin.', 'Torka luckkant, tätning och gångjärnszon varsamt.', 'Ta bort matrester utan att dra i tätningen.'], done: 'Tätning och luckkant är rena och oskadade.' }),
  micro({ id: 'micro-sink-strainer', roomId: 'kitchen', title: 'Rengör diskhons sil', category: 'hygiene', minutes: 5, everyDays: 7, priority: 69, bundleKey: 'kitchen-sink-details', bundleLabel: 'Ta diskhons smådetaljer', tools: ['Diskborste'], products: ['Diskmedel'], steps: ['Töm silen.', 'Diska sil, propp och den åtkomliga kanten.', 'Skölj och sätt tillbaka.'], done: 'Silen är fri från matrester och sitter på plats.' }),
  micro({ id: 'micro-under-sink-floor', roomId: 'kitchen', title: 'Torka botten under diskhon', category: 'hygiene', minutes: 8, everyDays: 90, priority: 54, bundleKey: 'kitchen-sink-details', bundleLabel: 'Ta diskhons smådetaljer', tools: ['Mikrofiberduk'], steps: ['Flytta ut lösa flaskor.', 'Kontrollera efter fukt eller läckage.', 'Torka botten och ställ tillbaka upprätt.'], done: 'Skåpsbotten är ren och torr utan tecken på läckage.', warnings: ['Vid fukt eller läckage: stoppa och åtgärda orsaken innan saker ställs tillbaka.'] }),

  micro({ id: 'micro-bathroom-mirror', roomId: 'upstairs-bathroom', title: 'Putsa badrumsspegeln', category: 'visible', minutes: 5, everyDays: 7, priority: 62, bundleKey: 'bathroom-details', bundleLabel: 'Putsa badrummets smådetaljer', products: ['Glasrengöring'], steps: ['Torka stänk från spegeln.', 'Putsa kanter och eftertorka utan ränder.'], done: 'Spegeln är fri från tydliga stänk och ränder.', guests: true }),
  micro({ id: 'micro-downstairs-bathroom-mirror', roomId: 'downstairs-bathroom', title: 'Putsa spegeln i badrummet nere', category: 'visible', minutes: 5, everyDays: 7, priority: 58, bundleKey: 'bathroom-details', bundleLabel: 'Putsa badrummens smådetaljer', products: ['Glasrengöring'], steps: ['Torka stänk från spegeln.', 'Putsa kanter och eftertorka utan ränder.'], done: 'Spegeln nere är fri från tydliga stänk och ränder.', guests: true }),
  micro({ id: 'micro-toothbrush-holder', roomId: 'upstairs-bathroom', title: 'Diska tandborstmuggen', category: 'hygiene', minutes: 5, everyDays: 7, priority: 68, bundleKey: 'bathroom-details', bundleLabel: 'Putsa badrummets smådetaljer', tools: ['Diskborste'], products: ['Diskmedel'], steps: ['Flytta tandborstar hygieniskt.', 'Diska mugg eller hållare och torka ytan under.', 'Låt torka innan återställning.'], done: 'Tandborsthållaren och ytan under är rena och torra.' }),
  micro({ id: 'micro-soap-dispenser', roomId: 'upstairs-bathroom', title: 'Torka tvålpump och flaskor', category: 'hygiene', minutes: 4, everyDays: 7, priority: 61, bundleKey: 'bathroom-details', bundleLabel: 'Putsa badrummets smådetaljer', products: ['Milt rengöringsmedel'], steps: ['Torka pump, flaskor och kladdiga bottnar.', 'Torka ytan under och fyll på vid behov.'], done: 'Tvålzonen är ren och fungerande.', guests: true }),
  micro({ id: 'micro-downstairs-soap-dispenser', roomId: 'downstairs-bathroom', title: 'Torka tvålpumpen i badrummet nere', category: 'hygiene', minutes: 4, everyDays: 7, priority: 57, bundleKey: 'bathroom-details', bundleLabel: 'Putsa badrummens smådetaljer', products: ['Milt rengöringsmedel'], steps: ['Torka pump, flaska och kladdig botten.', 'Torka ytan under och fyll på vid behov.'], done: 'Tvålzonen nere är ren och fungerande.', guests: true }),
  micro({ id: 'micro-toilet-hinges', roomId: 'upstairs-bathroom', title: 'Rengör toalettens gångjärn och fot', category: 'hygiene', minutes: 7, everyDays: 7, priority: 73, bundleKey: 'bathroom-toilet', bundleLabel: 'Ta toalettens missade ytor', tools: ['Separat mikrofiberduk'], products: ['Badrumsrengöring'], steps: ['Använd en duk avsedd för toaletten.', 'Torka gångjärn, sitsfästen, utsida och fot.', 'Eftertorka och tvätta händerna.'], done: 'Toalettens gångjärn, fästen och fot är rena.' }),
  micro({ id: 'micro-downstairs-toilet-hinges', roomId: 'downstairs-bathroom', title: 'Rengör toalettens gångjärn och fot nere', category: 'hygiene', minutes: 7, everyDays: 14, priority: 62, bundleKey: 'bathroom-toilet', bundleLabel: 'Ta toaletternas missade ytor', tools: ['Separat mikrofiberduk'], products: ['Badrumsrengöring'], steps: ['Använd en duk avsedd för toaletten.', 'Torka gångjärn, sitsfästen, utsida och fot.', 'Eftertorka och tvätta händerna.'], done: 'Toalettens gångjärn, fästen och fot nere är rena.' }),
  micro({ id: 'micro-behind-toilet', roomId: 'upstairs-bathroom', title: 'Torka golvet bakom toaletten', category: 'floor', minutes: 7, everyDays: 14, priority: 66, bundleKey: 'bathroom-toilet', bundleLabel: 'Ta toalettens missade ytor', tools: ['Separat duk eller liten mopp'], products: ['Golvrengöring'], steps: ['Flytta bara lösa föremål.', 'Torka golv och åtkomliga rör bakom toaletten.', 'Låt torka och ställ tillbaka.'], done: 'Åtkomligt golv bakom toaletten är rent och torrt.' }),
  micro({ id: 'micro-shower-hair', roomId: 'upstairs-bathroom', title: 'Ta hår från duschens sil', category: 'hygiene', minutes: 5, everyDays: 7, priority: 78, bundleKey: 'bathroom-shower', bundleLabel: 'Ta duschens smådetaljer', tools: ['Skyddshandskar', 'Papper'], steps: ['Lyft bara den användaråtkomliga silen.', 'Ta bort hår och skräp.', 'Skölj silen och sätt tillbaka den korrekt.'], done: 'Silen är fri från hår och vattnet kan rinna undan.' }),
  micro({ id: 'micro-shower-track', roomId: 'upstairs-bathroom', title: 'Borsta duschväggens nederkant', category: 'hygiene', minutes: 8, everyDays: 14, priority: 65, bundleKey: 'bathroom-shower', bundleLabel: 'Ta duschens smådetaljer', tools: ['Mjuk borste'], products: ['Materialanpassat badrumsmedel'], steps: ['Borsta skena, list och hörn där tvål samlas.', 'Skölj och torka torrt.'], done: 'Duschväggens nederkant och skena är fria från synlig beläggning.' }),
  micro({ id: 'micro-tile-splashes', roomId: 'upstairs-bathroom', title: 'Torka kaklets stänkzon', category: 'hygiene', minutes: 8, everyDays: 14, priority: 58, bundleKey: 'bathroom-shower', bundleLabel: 'Ta duschens smådetaljer', products: ['Materialanpassat badrumsmedel'], steps: ['Välj den mest utsatta stänkzonen.', 'Torka kakel och fogytor varsamt.', 'Skölj bort produktrester och torka.'], done: 'Den valda stänkzonen är fri från synliga tvålrester.' }),
  micro({ id: 'micro-bathroom-pipes', roomId: 'upstairs-bathroom', title: 'Torka synliga rör', category: 'visible', minutes: 6, everyDays: 30, priority: 46, bundleKey: 'bathroom-fixtures', bundleLabel: 'Damma badrummets fasta detaljer', tools: ['Mikrofiberduk'], steps: ['Damma rörens ovansidor.', 'Torka lätt fuktigt där materialet tillåter.', 'Kontrollera samtidigt efter fukt.'], done: 'Synliga rör är dammfria och torra.' }),
  micro({ id: 'micro-bathroom-vent', roomId: 'upstairs-bathroom', title: 'Damma badrumsventilens utsida', category: 'visible', minutes: 5, everyDays: 30, priority: 58, bundleKey: 'bathroom-fixtures', bundleLabel: 'Damma badrummets fasta detaljer', tools: ['Dammsugare med borste'], steps: ['Dammsug eller torka ventilens utsida försiktigt.', 'Låt inställning och don sitta kvar.'], done: 'Ventilens utsida är fri från synligt damm.', warnings: ['Ändra inte ventilens inställning och demontera den inte utan instruktion.'] }),
  micro({ id: 'micro-bathroom-fronts', roomId: 'upstairs-bathroom', title: 'Torka badrumsskåpets fronter', category: 'visible', minutes: 6, everyDays: 14, priority: 54, bundleKey: 'bathroom-fixtures', bundleLabel: 'Damma badrummets fasta detaljer', products: ['Milt materialanpassat medel'], steps: ['Torka fronter, kanter och handtag.', 'Eftertorka torrt.'], done: 'Badrumsskåpets utsida är fri från stänk och fingeravtryck.' }),
  micro({ id: 'micro-laundry-hamper', roomId: 'upstairs-bathroom', title: 'Torka ur tvättkorgen', category: 'laundry', minutes: 7, everyDays: 30, priority: 48, bundleKey: 'bathroom-textiles', bundleLabel: 'Byt badrummens textilier', products: ['Milt rengöringsmedel'], steps: ['Töm korgen.', 'Dammsug ludd och torka insidan.', 'Låt torka innan tvätt läggs tillbaka.'], done: 'Tvättkorgen är ren och torr.' }),

  micro({ id: 'micro-switches', roomId: 'middle-hall', title: 'Torka strömbrytarnas utsidor', category: 'hygiene', minutes: 8, everyDays: 14, priority: 64, bundleKey: 'house-contact-points', bundleLabel: 'Ta husets kontaktpunkter', tools: ['Torr eller mycket lätt fuktad duk'], steps: ['Välj ett våningsplan.', 'Torka brytarnas utsidor utan att vätska når springor.', 'Ta synliga märken runt plattan varsamt.'], done: 'Valda strömbrytare är fria från fingeravtryck.', warnings: ['Spraya aldrig vätska på strömbrytare eller uttag.'], guests: true }),
  micro({ id: 'micro-door-handles', roomId: 'middle-hall', title: 'Torka dörrhandtag', category: 'hygiene', minutes: 8, everyDays: 14, priority: 66, bundleKey: 'house-contact-points', bundleLabel: 'Ta husets kontaktpunkter', products: ['Milt rengöringsmedel'], steps: ['Välj ett våningsplan.', 'Torka handtag, trycken och greppzoner.', 'Eftertorka torrt.'], done: 'Valda handtag känns rena.', guests: true }),
  micro({ id: 'micro-door-tops', roomId: 'middle-hall', title: 'Damma dörrarnas överkanter', category: 'visible', minutes: 8, everyDays: 90, priority: 42, bundleKey: 'house-edges', bundleLabel: 'Ta husets kanter och lister', tools: ['Dammduk'], steps: ['Välj ett våningsplan.', 'Damma överkanter på dörrblad och karmar.', 'Dammsug nedfallet.'], done: 'Valda dörr- och karmöverkanter är dammfria.' }),
  micro({ id: 'micro-thresholds', roomId: 'middle-hall', title: 'Torka trösklar', category: 'floor', minutes: 8, everyDays: 30, priority: 48, bundleKey: 'house-edges', bundleLabel: 'Ta husets kanter och lister', products: ['Materialanpassat golvmedel'], steps: ['Dammsug springor runt trösklarna.', 'Torka ovansidor och kanter.', 'Eftertorka trä sparsamt.'], done: 'Valda trösklar och springor är rena.' }),
  micro({ id: 'micro-skirting', roomId: 'middle-hall', title: 'Torka golvlister på ett våningsplan', category: 'visible', minutes: 12, everyDays: 30, priority: 52, bundleKey: 'house-edges', bundleLabel: 'Ta husets kanter och lister', tools: ['Dammsugare med borste', 'Mikrofiberduk'], steps: ['Dammsug löst damm först.', 'Torka listernas ovansidor och synliga märken.', 'Arbeta ett våningsplan i taget.'], done: 'Ett våningsplans åtkomliga golvlister är dammfria.' }),
  micro({ id: 'micro-window-sills', roomId: 'living-room', title: 'Torka fönsterbrädor', category: 'visible', minutes: 8, everyDays: 14, priority: 54, bundleKey: 'window-details', bundleLabel: 'Ta fönstrens detaljer', products: ['Milt materialanpassat medel'], steps: ['Flytta växter och prydnader från en fönstergrupp.', 'Torka brädor och nedersta karmkant.', 'Ställ tillbaka utan vattenringar.'], done: 'Valda fönsterbrädor är rena och torra.', guests: true }),
  micro({ id: 'micro-blinds', roomId: 'living-room', title: 'Damma en grupp persienner', category: 'visible', minutes: 12, everyDays: 90, priority: 40, bundleKey: 'window-details', bundleLabel: 'Ta fönstrens detaljer', tools: ['Dammvippa eller mikrofiberduk'], steps: ['Stäng persiennen åt ena hållet och damma.', 'Vänd och upprepa.', 'Torka snören och reglage torrt.'], done: 'Valda persienner är fria från synligt damm.' }),
  micro({ id: 'micro-lampshades', roomId: 'living-room', title: 'Damma lampskärmar', category: 'visible', minutes: 8, everyDays: 30, priority: 50, bundleKey: 'lighting-details', bundleLabel: 'Damma husets lampor', tools: ['Dammvippa eller mjuk dammsugarborste'], steps: ['Släck och låt lamporna svalna.', 'Damma skärmarnas utsidor och lampfötter.', 'Dammsug ytan under vid behov.'], done: 'Valda lampskärmar och lampfötter är dammfria.' }),
  micro({ id: 'micro-ceiling-lights', roomId: 'middle-hall', title: 'Torka taklampornas utsidor', category: 'visible', minutes: 10, everyDays: 90, priority: 44, bundleKey: 'lighting-details', bundleLabel: 'Damma husets lampor', tools: ['Stabil trappstege', 'Torr mikrofiberduk'], steps: ['Släck och låt armaturen svalna.', 'Torka endast säkert åtkomliga utsidor.', 'Dammsug nedfallet.'], done: 'Valda armaturers utsidor är dammfria.', childFriendly: false, warnings: ['Öppna inte armaturen. Använd stabil trappstege, aldrig stol.'] }),
  micro({ id: 'micro-cobwebs', roomId: 'middle-hall', title: 'Ta spindelväv i takvinklar', category: 'visible', minutes: 8, everyDays: 30, priority: 51, bundleKey: 'high-dusting', bundleLabel: 'Ta de höga dammytorna', tools: ['Förlängningsbar dammvippa'], steps: ['Gå ett våningsplan och titta längs takvinklar.', 'Ta spindelväv med förlängningsbart redskap.', 'Dammsug nedfallet.'], done: 'Ett våningsplans takvinklar är fria från synlig spindelväv.' }),
  micro({ id: 'micro-radiator-fronts', roomId: 'living-room', title: 'Damma elementens ovansidor', category: 'visible', minutes: 10, everyDays: 30, priority: 49, bundleKey: 'high-dusting', bundleLabel: 'Ta de höga dammytorna', tools: ['Dammsugare med borste', 'Mikrofiberduk'], steps: ['Låt elementen svalna.', 'Dammsug ovansidor och åtkomliga springor.', 'Torka framsidan lätt.'], done: 'Valda elements ovansidor och fronter är dammfria.' }),
  micro({ id: 'micro-vent-covers', roomId: 'living-room', title: 'Damma ventilernas utsidor', category: 'visible', minutes: 8, everyDays: 30, priority: 53, bundleKey: 'high-dusting', bundleLabel: 'Ta de höga dammytorna', tools: ['Dammsugare med mjuk borste'], steps: ['Dammsug utsidan på valda till- och frånluftsventiler.', 'Torka kanten torrt utan att vrida donet.'], done: 'Valda ventilationsdon är fria från synligt ytligt damm.', warnings: ['Ändra inte ventilernas inställning och demontera dem inte utan instruktion.'] }),
  micro({ id: 'micro-picture-frames', roomId: 'living-room', title: 'Damma tavlor och ramar', category: 'visible', minutes: 8, everyDays: 30, priority: 38, bundleKey: 'living-details', bundleLabel: 'Ta vardagsrummets detaljer', tools: ['Torr mikrofiberduk'], steps: ['Damma ramarnas ovansidor och framsidor.', 'Torka glas varsamt om det behövs.', 'Kontrollera att allt hänger stabilt.'], done: 'Valda ramar är dammfria och sitter stabilt.' }),
  micro({ id: 'micro-remotes', roomId: 'living-room', title: 'Torka fjärrkontroller och handkontroller', category: 'hygiene', minutes: 5, everyDays: 7, priority: 56, bundleKey: 'living-details', bundleLabel: 'Ta vardagsrummets detaljer', tools: ['Lätt fuktad mikrofiberduk'], steps: ['Stäng av utrustning vid behov.', 'Torka utsidor och knappar utan att vätska når springor.', 'Lägg tillbaka på bestämd plats.'], done: 'Kontrollerna är rena och samlade.' }),
  micro({ id: 'micro-plant-leaves', roomId: 'living-room', title: 'Damma stora växtblad', category: 'visible', minutes: 8, everyDays: 30, priority: 32, bundleKey: 'living-details', bundleLabel: 'Ta vardagsrummets detaljer', tools: ['Fuktad mjuk duk'], steps: ['Välj växter med stora, tåliga blad.', 'Stöd bladet och torka varsamt.', 'Ta bort torra nedfallna blad.'], done: 'Valda växters blad är fria från synligt damm.' }),
  micro({ id: 'micro-sofa-crumbs', roomId: 'living-room', title: 'Dammsug soffans synliga smulor', category: 'floor', minutes: 8, everyDays: 14, priority: 58, bundleKey: 'sofa-details', bundleLabel: 'Ta soffans dolda smulor', tools: ['Dammsugare med möbelmunstycke'], steps: ['Ta bort lösa filtar och kuddar.', 'Dammsug sittytor och synliga springor.', 'Lägg tillbaka textilier ordnat.'], done: 'Soffans synliga ytor är fria från smulor och hår.', guests: true }),
  micro({ id: 'micro-under-cushions', roomId: 'living-room', title: 'Dammsug under soffkuddarna', category: 'floor', minutes: 10, everyDays: 30, priority: 52, bundleKey: 'sofa-details', bundleLabel: 'Ta soffans dolda smulor', tools: ['Dammsugare med möbelmunstycke'], steps: ['Lyft lösa kuddar en i taget.', 'Samla saker som ramlat ner.', 'Dammsug springor och ytan under.', 'Lägg tillbaka kuddarna rätt.'], done: 'Det är rent under soffans lösa kuddar.' }),
  micro({ id: 'micro-table-legs', roomId: 'living-room', title: 'Torka bordets ben och undersida', category: 'visible', minutes: 8, everyDays: 30, priority: 42, bundleKey: 'dining-details', bundleLabel: 'Ta matplatsens missade ytor', products: ['Materialanpassat milt medel'], steps: ['Torka bordskantens undersida.', 'Torka ben och tvärslåar.', 'Ta synliga märken på stolarnas ben.'], done: 'Matbordets undersida och åtkomliga ben är rena.' }),
  micro({ id: 'micro-stair-handrail', roomId: 'upstairs-hall', title: 'Torka trappräcken och handledare', category: 'hygiene', minutes: 7, everyDays: 7, priority: 60, bundleKey: 'hall-details', bundleLabel: 'Ta hallens kontaktpunkter', products: ['Materialanpassat milt medel'], steps: ['Torka handledaren uppifrån och ner.', 'Ta greppytor och stolpar.', 'Eftertorka torrt.'], done: 'Trappräcken och handledare känns rena.', guests: true }),
  micro({ id: 'micro-entry-door', roomId: 'middle-hall', title: 'Torka ytterdörrens insida', category: 'visible', minutes: 8, everyDays: 14, priority: 55, bundleKey: 'hall-details', bundleLabel: 'Ta hallens kontaktpunkter', products: ['Materialanpassat milt medel'], steps: ['Torka handtag, låszon och dörrbladets synliga märken.', 'Torka karmens greppzon och tröskel.', 'Eftertorka torrt.'], done: 'Ytterdörrens insida och kontaktpunkter är rena.', guests: true }),
  micro({ id: 'micro-shoe-shelf', roomId: 'middle-hall', title: 'Torka skohyllan', category: 'floor', minutes: 8, everyDays: 14, priority: 54, bundleKey: 'hall-floor-details', bundleLabel: 'Återställ hallgolvets detaljer', tools: ['Dammsugare', 'Mikrofiberduk'], steps: ['Flytta skorna från en sektion.', 'Dammsug grus och torka hyllan.', 'Ställ tillbaka aktuella skor parvis.'], done: 'En sektion av skohyllan är fri från grus och smuts.', guests: true }),
  micro({ id: 'micro-doormats', roomId: 'middle-hall', title: 'Skaka och dammsug dörrmattor', category: 'floor', minutes: 7, everyDays: 7, priority: 63, bundleKey: 'hall-floor-details', bundleLabel: 'Återställ hallgolvets detaljer', tools: ['Dammsugare'], steps: ['Skaka mattan utomhus om det kan göras utan att störa.', 'Dammsug båda sidor där materialet tillåter.', 'Dammsug golvet under och lägg tillbaka plant.'], done: 'Dörrmattor och golvet under är fria från löst grus.', guests: true }),
  micro({ id: 'micro-headboard', roomId: 'bedroom-1', title: 'Damma sänggaveln', category: 'visible', minutes: 6, everyDays: 30, priority: 40, bundleKey: 'bedroom-details', bundleLabel: 'Ta sovrummets smådetaljer', tools: ['Dammsugare med mjuk borste eller duk'], steps: ['Välj metod efter material.', 'Damma ovansida, framsida och åtkomliga kanter.', 'Dammsug nedfallet.'], done: 'Sänggaveln är fri från synligt damm.' }),
  micro({ id: 'micro-bedside-lamp', roomId: 'bedroom-1', title: 'Damma sänglampor och sladdzon', category: 'visible', minutes: 6, everyDays: 30, priority: 39, bundleKey: 'bedroom-details', bundleLabel: 'Ta sovrummets smådetaljer', tools: ['Torr mikrofiberduk'], steps: ['Släck och låt lampan svalna.', 'Damma skärm, fot och bordets sladdzon.', 'Ordna kabeln utan att klämma den.'], done: 'Sänglampan och området runt den är dammfria.', warnings: ['Använd ingen våt duk på stickpropp, brytare eller lamphållare.'] }),
  micro({ id: 'micro-under-bed-edge', roomId: 'bedroom-1', title: 'Dammsug kanten under sängen', category: 'floor', minutes: 8, everyDays: 14, priority: 50, bundleKey: 'bedroom-floor-details', bundleLabel: 'Ta sovrummets dolda golv', tools: ['Dammsugare med långt munstycke'], steps: ['Ta bort saker som ligger precis vid kanten.', 'Dammsug så långt munstycket når utan att flytta tung säng.', 'Lägg tillbaka bara avsedd förvaring.'], done: 'Den åtkomliga golvkanten under sängen är dammfri.' }),
];
