import type { Task } from './taskEngine';

/**
 * Indoor long-cycle work inspired by professional move-clean coverage.
 * These tasks never enter ordinary sessions; the weekly recommender exposes
 * one at a time when its interval is due.
 */
export const professionalTasks: Task[] = [
  {
    id: 'care-bathroom-deep-clean', roomId: 'upstairs-bathroom', title: 'Storstäda badrummet som behöver det mest', category: 'hygiene', durationMinutes: 50, effort: 3,
    tools: ['Mikrofiberdukar', 'Toalettborste', 'Dammsugare', 'Mopp'], products: ['Badrumsrengöring som ytorna tål'],
    steps: ['Välj det badrum som behöver insatsen mest och plocka undan.', 'Arbeta uppifrån och ner över spegel, skåp, handfat, dusch eller badkar och toalett.', 'Rengör kontaktpunkter, fronter och synliga fogar.', 'Dammsug och våttorka golvet; lägg fram rena handdukar.'],
    doneDefinition: ['Det valda badrummet är rengjort från höga ytor till golv och klart att använda.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Blanda aldrig olika rengöringsmedel och ventilera under arbetet.'], recommendationOnly: true, recurrenceDays: 14, recommendationPriority: 96,
    repeatGroup: 'bathroom-deep-clean', recommendationReason: 'Ett badrum behöver regelbundet ett helt pass, inte bara handfat och toalett i förbifarten.',
  },
  {
    id: 'care-bathroom-drains', roomId: 'upstairs-bathroom', title: 'Rensa golvbrunn och vattenlås', category: 'hygiene', durationMinutes: 25, effort: 2,
    tools: ['Skyddshandskar', 'Hink', 'Borste', 'Gamla handdukar'],
    steps: ['Läs instruktionen för golvbrunnen och vattenlåset.', 'Ta bort hår och beläggningar mekaniskt.', 'Rengör löstagbara delar, montera tillbaka och spola försiktigt.', 'Kontrollera att inget läcker och att vattenlåset är vattenfyllt.'],
    doneDefinition: ['Vattnet rinner undan och alla delar sitter tätt på rätt plats.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Blanda aldrig propplösare med andra rengöringsmedel.', 'Avbryt och kontakta fackperson vid återkommande stopp, läckage eller osäker demontering.'],
    recommendationOnly: true, recurrenceDays: 30, recommendationPriority: 100,
    recommendationReason: 'Regelbunden mekanisk rensning förebygger lukt och gör att begynnande stopp upptäcks tidigt.',
  },
  {
    id: 'care-dishwasher-filter', roomId: 'kitchen', title: 'Rengör diskmaskinens filter', category: 'hygiene', durationMinutes: 15, effort: 1,
    tools: ['Diskborste', 'Mikrofiberduk'], products: ['Diskmedel'],
    steps: ['Stäng av maskinen och följ manualen för att ta ut filtret.', 'Ta bort matrester och diska filtret.', 'Torka runt sil och luckans tätning.', 'Montera filtret korrekt innan maskinen används.'],
    doneDefinition: ['Filtret är rent och sitter låst enligt manualen.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Akta glasskärvor och andra vassa föremål i filtret.'], recommendationOnly: true, recurrenceDays: 30, recommendationPriority: 92,
    recommendationReason: 'Ett rent filter minskar lukt och hjälper diskmaskinen att arbeta som den ska.',
  },
  {
    id: 'care-dryer-airflow', roomId: 'laundry-room', title: 'Rengör torktumlarens luftvägar', category: 'laundry', durationMinutes: 20, effort: 2,
    tools: ['Dammsugare', 'Mjuk borste', 'Mikrofiberduk'],
    steps: ['Stäng av maskinen och följ dess manual.', 'Rengör luddfilter och filterfack.', 'Rengör värmeväxlare eller kondensor endast om manualen anger att användaren ska göra det.', 'Dammsug löst ludd runt maskinens åtkomliga ventilationsytor.'],
    doneDefinition: ['Filter och användaråtkomliga luftvägar är fria från ludd och korrekt återmonterade.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Öppna inga servicepaneler och använd inte maskinen utan korrekt monterade filter.'], recommendationOnly: true, recurrenceDays: 30, recommendationPriority: 98,
    recommendationReason: 'Ludd försämrar luftflödet och kan bidra till överhettning och brandrisk.',
  },
  {
    id: 'care-washer-filter', roomId: 'laundry-room', title: 'Sköt om tvättmaskinens filter och tätning', category: 'laundry', durationMinutes: 25, effort: 2,
    tools: ['Låg skål', 'Gamla handdukar', 'Mikrofiberduk'],
    steps: ['Stäng av maskinen och följ manualens instruktion för nålfilter.', 'Skydda golvet och tappa ur eventuellt vatten kontrollerat.', 'Rengör filter, lucktätning och tvättmedelsfack.', 'Montera tillbaka och kontrollera täthet vid nästa övervakade körning.'],
    doneDefinition: ['Filter, tätning och fack är rena och inget läcker.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Öppna inte filtret om maskinen innehåller hett vatten.'], recommendationOnly: true, recurrenceDays: 60, recommendationPriority: 88,
    recommendationReason: 'Smuts i filter och tätningar kan ge lukt, sämre avrinning och läckage.',
  },
  {
    id: 'care-range-hood', roomId: 'kitchen', title: 'Avfetta köksfläktens filter', category: 'hygiene', durationMinutes: 30, effort: 2,
    tools: ['Diskborste', 'Diskbalja', 'Mikrofiberduk'], products: ['Diskmedel eller produkt godkänd i manualen'],
    steps: ['Stäng av fläkten och ta loss filtret enligt manualen.', 'Rengör fettfiltret med den metod tillverkaren anger.', 'Torka fläktens åtkomliga utsida och kanter.', 'Låt filtret torka helt och montera tillbaka det.'],
    doneDefinition: ['Filtret är fettfritt, torrt och korrekt monterat.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Rengör inte motor eller elektriska delar med vätska.'], recommendationOnly: true, recurrenceDays: 60, recommendationPriority: 90,
    recommendationReason: 'Fett i filtret försämrar funktionen och är en onödig brandbelastning.',
  },
  {
    id: 'care-bathroom-limescale', roomId: 'upstairs-bathroom', title: 'Avkalka dusch och blandare', category: 'hygiene', durationMinutes: 35, effort: 2,
    tools: ['Mjuk borste', 'Mikrofiberdukar'], products: ['Medel lämpligt för rummets material'],
    steps: ['Kontrollera material och produktens etikett.', 'Bearbeta duschvägg, blandare, duschhuvud och fogar varsamt.', 'Skölj noggrant och torka torrt.', 'Notera skadade fogar eller silikon för separat åtgärd.'],
    doneDefinition: ['Synliga kalk- och tvålrester är borta utan att ytorna skadats.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Blanda aldrig sur avkalkning med klorin eller andra rengöringsmedel.'], recommendationOnly: true, recurrenceDays: 60, recommendationPriority: 86,
    recommendationReason: 'Kalk och tvålfilm byggs upp långsamt och kräver ett eget, materialanpassat pass.',
  },
  {
    id: 'care-oven', roomId: 'kitchen', title: 'Rengör ugnen ordentligt', category: 'hygiene', durationMinutes: 50, effort: 3,
    tools: ['Skyddshandskar', 'Mjuk svamp', 'Mikrofiberdukar'], products: ['Ugnsrengöring godkänd i manualen'],
    steps: ['Låt ugnen svalna helt och läs manualen.', 'Ta ut och rengör plåtar och galler.', 'Rengör ugnsutrymme, luckans insida och tätning enligt tillverkarens råd.', 'Torka bort alla produktrester och montera tillbaka delarna.'],
    doneDefinition: ['Ugn, plåtar och galler är fria från lösa mat- och fettrester.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Använd aldrig rengöringsmedel samtidigt med pyrolysprogram. Ventilera och följ produktetiketten.'], recommendationOnly: true, recurrenceDays: 90, recommendationPriority: 82,
    recommendationReason: 'Ugnsfett blir betydligt svårare att ta bort när det får byggas på kvartal efter kvartal.',
  },
  {
    id: 'care-fridge-interior', roomId: 'kitchen', title: 'Töm och rengör kylskåpet', category: 'hygiene', durationMinutes: 40, effort: 2,
    tools: ['Kylväska', 'Mikrofiberdukar'], products: ['Milt diskmedel'],
    steps: ['Flytta kylvaror till kylväska och följ manualens avstängningsråd.', 'Ta ut och handdiska lösa hyllor och lådor om manualen tillåter.', 'Torka insida, avrinningsränna och dörrtätningar.', 'Torka torrt, starta vid behov och ställ tillbaka kontrollerade varor.'],
    doneDefinition: ['Kylens ytor och tätningar är rena och gamla varor är borttagna.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Låt glashyllor bli rumstempererade före rengöring för att undvika temperaturchock.'], recommendationOnly: true, recurrenceDays: 90, recommendationPriority: 84,
    recommendationReason: 'Ett tomt kylskåp avslöjar spill, blockerad avrinning och mat som passerat sitt bäst före.',
  },
  {
    id: 'care-under-furniture', roomId: 'living-room', title: 'Städa under tunga möbler', category: 'floor', durationMinutes: 40, effort: 3,
    tools: ['Möbeltassar', 'Dammsugare', 'Mopp'],
    steps: ['Välj bara möbler som kan flyttas säkert.', 'Var två vid tunga eller otympliga möbler.', 'Dammsug och torka golv, väggkant och möbelns baksida.', 'Ställ tillbaka utan att klämma kablar.'],
    doneDefinition: ['Åtkomliga ytor under och bakom valda möbler är rena och möblerna står stabilt.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Lyft inte tungt ensam och flytta inte väggförankrade möbler.'], recommendationOnly: true, recurrenceDays: 90, recommendationPriority: 72,
    recommendationReason: 'Damm, hår och småsaker samlas där den vanliga dammsugningen inte når.',
  },
  {
    id: 'care-high-dusting', roomId: 'living-room', title: 'Damma höga och bortglömda ytor', category: 'visible', durationMinutes: 35, effort: 2,
    tools: ['Stabil trappstege', 'Förlängningsbar dammvippa', 'Dammsugare'],
    steps: ['Arbeta uppifrån och ner: ovansidor på skåp, dörrkarmar och höga hyllor.', 'Damma ventilernas utsida utan att demontera dem.', 'Damma fast belysning endast när den är avstängd och sval.', 'Dammsug nedfallet sist.'],
    doneDefinition: ['De valda höga ytorna är dammfria och golvet är uppsamlat.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Använd stabil trappstege, aldrig stol. Öppna inte elarmaturer eller ventilationssystem.'], recommendationOnly: true, recurrenceDays: 90, recommendationPriority: 76,
    recommendationReason: 'Proffs arbetar uppifrån och ner eftersom högt damm annars faller på redan rengjorda ytor.',
  },
  {
    id: 'care-doors-trim', roomId: 'middle-hall', title: 'Tvätta lister, dörrar och karmar', category: 'visible', durationMinutes: 45, effort: 2,
    tools: ['Mikrofiberdukar', 'Mjuk borste'], products: ['Milt rengöringsmedel'],
    steps: ['Dammsug lister och karmarnas överkanter.', 'Punktbehandla märken efter materialets tålighet.', 'Torka dörrblad, karmar, handtag och strömbrytarnas utsidor.', 'Torka torrt.'],
    doneDefinition: ['Ett sammanhängande våningsplans lister, dörrar och karmar är rena.'], modes: ['weekend'], childFriendly: true,
    safetyWarnings: ['Spraya aldrig vätska direkt på strömbrytare eller uttag.'], recommendationOnly: true, recurrenceDays: 90, recommendationPriority: 70,
    recommendationReason: 'Kanter och kontaktpunkter är typiska flyttstädsmoment som vardagsstädningen missar.',
  },
  {
    id: 'care-cabinets', roomId: 'kitchen', title: 'Rengör skåp och lådor invändigt', category: 'hygiene', durationMinutes: 50, effort: 2,
    tools: ['Korgar', 'Dammsugare', 'Mikrofiberdukar'], products: ['Milt rengöringsmedel'],
    steps: ['Välj en hanterbar sektion och töm den.', 'Sortera bort utgånget eller sådant som inte används.', 'Dammsug smulor och torka hyllor, lådor och fronter.', 'Låt torka och ställ tillbaka grupperat.'],
    doneDefinition: ['Den valda sektionen är ren, torr och överskådlig inuti och utanpå.'], modes: ['weekend'], childFriendly: true,
    recommendationOnly: true, recurrenceDays: 180, recommendationPriority: 62,
    recommendationReason: 'Invändiga skåp ingår i professionell helhetsstädning men behöver delas upp hemma.',
  },
  {
    id: 'care-radiators', roomId: 'living-room', title: 'Rengör element fram och bakom', category: 'visible', durationMinutes: 40, effort: 2,
    tools: ['Elementborste', 'Dammsugare', 'Mikrofiberduk'],
    steps: ['Stäng av eller låt elementen svalna.', 'Skydda golvet och dammsug löst damm.', 'Använd elementborste på åtkomliga ytor bakom och mellan.', 'Torka utsidan lätt fuktigt och sedan torrt.'],
    doneDefinition: ['Åtkomliga ytor på, under och bakom elementen är dammfria.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Demontera inte fasta element och använd inte mycket vatten nära elanslutningar.'], recommendationOnly: true, recurrenceDays: 180, recommendationPriority: 68,
    recommendationReason: 'Elementens baksidor samlar damm som vanlig ytrengöring inte når.',
  },
  {
    id: 'care-windows', roomId: 'living-room', title: 'Putsa fönster och rengör bågar', category: 'visible', durationMinutes: 60, effort: 3,
    tools: ['Fönsterskrapa', 'Mikrofiberdukar', 'Hink'], products: ['Fönsterputs'],
    steps: ['Välj en våning eller tydlig grupp fönster.', 'Dammsug eller torka karmar och bågar.', 'Putsa åtkomliga glasytor på in- och utsida.', 'Torka kanter och fönsterbrädor.'],
    doneDefinition: ['Valda fönster, karmar och brädor är rena utan tydliga ränder.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Luta dig aldrig ut genom fönster och arbeta inte på osäker höjd. Anlita hjälp för oåtkomliga utsidor.'], recommendationOnly: true, recurrenceDays: 180, recommendationPriority: 66,
    recommendationReason: 'Fönster på båda sidor samt karmar och brädor är en central del av flyttstädning.',
    activeMonths: [4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: 'care-mattresses', roomId: 'bedroom-1', title: 'Fräscha upp madrasser och sängzon', category: 'hygiene', durationMinutes: 40, effort: 2,
    tools: ['Dammsugare med möbelmunstycke', 'Tvättkorg'],
    steps: ['Ta av och tvätta sängkläder enligt etiketten.', 'Dammsug madrassens åtkomliga sidor och sängramen.', 'Rotera madrassen om tillverkaren rekommenderar det.', 'Dammsug under sängen och bädda rent.'],
    doneDefinition: ['Madrass, sängram och golvet under är dammsugna och sängen är renbäddad.'], modes: ['weekend'], childFriendly: true,
    safetyWarnings: ['Vänd eller lyft inte en tung madrass ensam.'], recommendationOnly: true, recurrenceDays: 180, recommendationPriority: 58,
    recommendationReason: 'Sängens dolda ytor samlar textildamm och blir sällan en del av vanliga pass.',
  },
  {
    id: 'care-behind-fridge', roomId: 'kitchen', title: 'Rengör bakom och under kyl/frys', category: 'floor', durationMinutes: 35, effort: 3,
    tools: ['Dammsugare', 'Mjuk borste', 'Mikrofiberduk'],
    steps: ['Läs manualen och kontrollera att apparaten får flyttas av användaren.', 'Stäng av och dra ur stickproppen om manualen anger det.', 'Var två, flytta bara så långt anslutningar tillåter och dammsug golv samt åtkomliga ventilationsytor.', 'Ställ tillbaka utan att klämma kabel och kontrollera att apparaten står stabilt.'],
    doneDefinition: ['Golv och användaråtkomliga ventilationsytor är rena och apparaten står korrekt.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Avbryt om apparaten är fast ansluten, inbyggd, svår att flytta eller om rör och kablar riskerar att skadas.'], recommendationOnly: true, recurrenceDays: 180, recommendationPriority: 74,
    recommendationReason: 'Damm runt kylens ventilation kan försämra kylningen och är ett vanligt bortglömt område.',
  },
  {
    id: 'care-behind-dryer', roomId: 'laundry-room', title: 'Städa bakom torktumlaren säkert', category: 'laundry', durationMinutes: 35, effort: 3,
    tools: ['Dammsugare', 'Mjuk borste', 'Skyddshandskar'],
    steps: ['Läs manualen och töm maskinens vattenbehållare.', 'Stäng av och koppla ur stickproppen om maskinen inte är fast ansluten.', 'Var två och flytta maskinen bara så långt slangar och kabel tillåter.', 'Dammsug golv, vägg och maskinens åtkomliga utsida; ställ tillbaka stabilt utan klämda anslutningar.'],
    doneDefinition: ['Löst ludd och damm bakom maskinen är borta och alla anslutningar ligger fritt.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Flytta aldrig en fast ansluten maskin. Är den staplad, inbyggd eller svåråtkomlig: boka fackhjälp i stället. Tunga apparater flyttas av två vuxna.'], recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 80,
    recommendationReason: 'Ludd bakom torktumlaren är både ett hygienproblem och en möjlig brandbelastning.',
  },
  {
    id: 'care-behind-stove', roomId: 'kitchen', title: 'Rengör bakom och under spisen', category: 'hygiene', durationMinutes: 35, effort: 3,
    tools: ['Dammsugare', 'Mikrofiberdukar', 'Skyddshandskar'], products: ['Avfettningsmedel lämpligt för ytorna'],
    steps: ['Läs spisens manual och kontrollera hur den får flyttas.', 'Stäng av, låt svalna och flytta den med två vuxna utan att belasta anslutningen.', 'Dammsug och rengör golv, vägg och spisens åtkomliga utsidor.', 'Ställ tillbaka stabilt utan klämd kabel eller rubbad anslutning.'],
    doneDefinition: ['Fett, smulor och damm bakom spisen är borta och spisen står säkert på rätt plats.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Dra inte ut eller koppla loss en fast ansluten spis. Vid osäker elanslutning, tippskydd eller passform: anlita fackperson.'], recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 78,
    recommendationReason: 'Bakom spisen samlas fett och matrester och området ingår normalt i en fullständig flyttstädning.',
  },
  {
    id: 'care-walls-ceilings', roomId: 'living-room', title: 'Gå igenom väggar och tak', category: 'visible', durationMinutes: 45, effort: 2,
    tools: ['Förlängningsbar dammvippa', 'Mikrofiberduk', 'Stabil trappstege'], products: ['Milt medel som ytskiktet tål'],
    steps: ['Damma takvinklar och ta bort spindelväv uppifrån och ner.', 'Punktbehandla tydliga märken på tvättbara väggar efter prov på dold yta.', 'Torka fönsterbrädor och fasta kanter i samma zon.', 'Dammsug nedfallet sist.'],
    doneDefinition: ['Takvinklar är fria från damm och spindelväv och valda väggmärken är varsamt åtgärdade.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Blöt inte tapet eller okänt ytskikt. Använd stabil trappstege och avbryt vid mögel eller fuktskada.'], recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 44,
    recommendationReason: 'Tak, väggar och fasta kanter kontrolleras vid flyttstädning men behöver bara lyftas sällan i ett bebott hem.',
  },
  {
    id: 'care-freezer-defrost', roomId: 'kitchen', title: 'Frosta av och rengör frysen', category: 'hygiene', durationMinutes: 60, effort: 3,
    tools: ['Kylväskor', 'Handdukar', 'Mikrofiberdukar'], products: ['Milt diskmedel'],
    steps: ['Planera matförvaringen och följ frysens manual.', 'Stäng av, töm och låt isen smälta med handdukar som fångar vatten.', 'Rengör och torka insida, lådor och tätningar.', 'Starta igen och lägg tillbaka maten först när temperaturen är säker.'],
    doneDefinition: ['Frysen är isfri, ren, torr och tillbaka vid säker temperatur.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Hacka aldrig loss is med kniv eller andra vassa föremål.'], recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 56,
    recommendationReason: 'Avfrostning och tom rengöring är ett stort moment som behöver bokas separat.',
  },
  {
    id: 'care-wardrobes', roomId: 'upstairs-hall', title: 'Töm och rengör garderober', category: 'visible', durationMinutes: 50, effort: 2,
    tools: ['Korgar', 'Dammsugare', 'Mikrofiberduk'],
    steps: ['Välj en garderob eller linneskåpssektion.', 'Töm och sortera innehållet.', 'Dammsug hyllor, lådor och botten; torka fasta ytor.', 'Låt torka och lägg tillbaka grupperat.'],
    doneDefinition: ['Den valda garderoben är ren invändigt och innehållet går att hitta.'], modes: ['weekend'], childFriendly: true,
    recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 48,
    recommendationReason: 'Professionell helhetsstädning tar även skåp och garderober invändigt.',
  },
  {
    id: 'care-fixed-lighting', roomId: 'middle-hall', title: 'Rengör fast belysning', category: 'visible', durationMinutes: 35, effort: 2,
    tools: ['Stabil trappstege', 'Torr mikrofiberduk'],
    steps: ['Släck och låt lamporna svalna helt.', 'Damma armaturernas utsidor och åtkomliga ovansidor.', 'Rengör lösa kupor endast om manualen visar att användaren kan ta loss dem.', 'Montera torra delar korrekt.'],
    doneDefinition: ['Åtkomliga armaturer är dammfria och korrekt monterade.'], modes: ['weekend'], childFriendly: false,
    safetyWarnings: ['Bryt strömmen före demontering. Vid fast el, skadade delar eller osäkerhet: anlita fackperson.'], recommendationOnly: true, recurrenceDays: 365, recommendationPriority: 46,
    recommendationReason: 'Fast belysning och armaturers ovansidor är typiska professionella kontrollpunkter.',
  },
];
